version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.13.4
    container_name: qdrant_db
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  rag-service:
    build: .
    container_name: rag-service
    restart: always
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    environment:
      QDRANT_HOST: "http://qdrant:6333"
      AZURE_OPENAI_ENDPOINT: "https://your-azure-openai-instance.openai.azure.com"
      AZURE_OPENAI_API_KEY: "your-api-key"
      AZURE_OPENAI_DEPLOYMENT_NAME: "gpt-4"
      AZURE_OPENAI_REGION: "eastus"
      HF_HOME: "/root/.cache/huggingface"  # ✅ Set Hugging Face cache location
      TRANSFORMERS_NO_ADVISORY_WARNINGS: "1"
      REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"  # ✅ Force correct CA bundle   

volumes:
  qdrant_data: