version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.13.4
    container_name: qdrant_db
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  rag-service:
    build: .
    container_name: rag_pipeline
    restart: always
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    environment:
      QDRANT_HOST: "http://qdrant:6333"

volumes:
  qdrant_data: